### ISSUE TITLE
Power and Performances settings error

### ISSUE THREAD

**Issue by levelKro** [levelKro/AI-Suite-III-Repack#1]
OS: Windows 10 X64
Latest AI Suite (3.00.52)

Problem: When you select the section about Power and Performances settings, you have a dialog box with error about a DLL.

Tried solution: Removed AI Suite and use the AI Suite Cleaner tool for remove all. Also tried to reinstall after a Windows 10 clean install.

* Need to be reproduced on other config for confirmation
* Need recreate error for get right error message

**Comment by ezeholz** [comment]
![image](https://user-images.githubusercontent.com/30635862/88696786-0dba9100-d0da-11ea-9507-34979622ac36.png)
Are you talking about this issue?

**Comment by levelKro** [comment]
Yes yes yes... this f*cking error message, you have a solution ?

**Comment by ezeholz** [comment]
Not at all, seems to be happening because of Fanxpert install. I uninstall it, and everything seems to be normal again. Let me research a few more about this.

**Comment by levelKro** [comment]
I confirm, remove Fan Xpert 2
Install Performance and Power Saving Utilities

After, you see PPSU and FanXpert 2

**Comment by levelKro** [comment]
Also, you can install USB3 Boost without problem.

**Comment by levelKro** [comment]
Added a Warning when install feature for NOT INSTALL FANXPERT if you install PPSU.
