### ISSUE TITLE
Fan RGB Control violation

### ISSUE THREAD

**Issue by ezeholz** [levelKro/AI-Suite-III-Repack#2]
![image](https://user-images.githubusercontent.com/30635862/88696410-9edd3800-d0d9-11ea-8dfb-bd1b230a65f5.png)
Every time I entered Fan RGB Control shows this.

Windows 10 x64

**Comment by levelKro** [comment]
I have got same error, remove this feature and re-install it. Or download package for 3.00.13 from Asus.

**Comment by ezeholz** [comment]
I downloaded package 2.00.12 with only FANRGBLEDControl 1.00.11, and seems to be working. It's anything we can do to add it into the repack?

**Comment by levelKro** [comment]
I have got this issue with my package, but if I install it with the original pack , it's work. I suggest the install executable have little info to setup Fan RGB correctly.
